manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://gitee.com/gofranchang
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: GofranChang
      url-base: https://github.com/GofranChang
  projects:
    - name: zmk
      remote: petejohanson
      revision: core/move-to-zephyr-4-1
      import: app/west.yml
    - name: analog-matrix-module
      remote: GofranChang
      revision: tako_dbg
  self:
    path: config
